@startuml カレーを作る
title カレーライス

start

:野菜を洗う;
:野菜を切る;
fork
    :肉を準備する;
    :米を炊く;
fork again
    :鍋を準備する;
end fork
:野菜を炒める;
:肉を炒める;
fork
    :水を入れて煮込む;
fork again
    :腹筋をして腹を減らす;
end fork
:カレーのルーを入れる;
:混ぜる;






